### ISSUE TITLE
CSS viewport units are causing a useless horizontal scrollbar

### ISSUE THREAD

**Issue by simevidas** [oddbird/sliiides#3]
Steps to reproduce:

1. On desktop, open https://slides.oddbird.net/csswg/f2f2102/
2. Switch to classic scrollbars if you’re on macOS

There will be a useless horizontal scrollbar on the page. See the screenshot below. This is caused by the use of CSS viewport units. I have [written about this issue](https://css-tricks.com/weekly-platform-news-reduced-motion-cors-whitehouse-gov-popups-and-100vw/#the-css-100vw-value-can-cause-a-useless-horizontal-scrollbar) for CSS-Tricks.

<img width="1280" alt="Screen Shot 2021-04-12 at 3 25 33 AM" src="https://user-images.githubusercontent.com/716405/114329106-d5ab8f00-9b3e-11eb-8c6c-e4b0b5741b54.png">

**Comment by mirisuzanne** [comment]
Fixed. Thanks for reporting it, @simevidas !
